server.port: 8092
spring:
  h2.console:
    enabled: true
    path: /h2-console
  jpa.properties.hibernate:
    show_sql: true
    use_sql_comments: true
    format_sql: true
    type: trace
logging:
  level:
    org:
      hibernate:
        type: trace


